site_name: Knowledge Graph Programming Language
nav:
  - Welcome: index.md
  - Tutorial: tutorial.md
  - Sharing Service: sharingservice.md
  - Knowledge Client: knowledgeclient.md
  - Lineage: lineage.md
  - REST API: restapi.md
  - Installation: install.md
  - API Documentation: api.md
  - About: about.md
theme: readthedocs

extra_css:
    - css/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
