import json
import pandas
import knps

pandas.set_option('display.max_rows', None)
pandas.set_option('display.max_columns', None)

def test1():
    r = knps.ORM.createRelation("Q458")
    r.extend("P150", False, "Countries")
    r.changeFocus("Countries")
    r.extend("P2131", False, "GDP")
    r.extend("P36", False, "Capitals")
    # r.changeFocus("Capitals")
    # r.extend("P1082", False, "Population_of_capitals")
    r.query()
    print(r.df)
    return r


def test4(rel):
    my_comment = "relationship generated by thrust 1"
    knps.publish_new(rel,my_comment,"RelationshipTest","Alice")

def test10():
    val = knps.get_label_content("RelationshipTest")
    # print(val)
    val.df.to_html('RelationTest')

if __name__ == "__main__":
    # relation_from_thrust_one = test1()
    # test4(relation_from_thrust_one)
    
    # Put them together
    # test8()
    # test9()
    test10()
