"""First migration

Revision ID: 3e27ccd50d88
Revises: 
Create Date: 2021-06-01 11:17:35.150763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e27ccd50d88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dataobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataobject_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('datatype', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dataobject_id'], ['dataobject.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ref_id'], ['dataobject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datacontents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('contents', sa.LargeBinary(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['dataversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataversion_predecessor',
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['dataversion.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dataversion.id'], )
    )
    op.create_table('dataversions_generator',
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('generator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generator_id'], ['dataversion.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dataversion.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataversions_generator')
    op.drop_table('dataversion_predecessor')
    op.drop_table('datacontents')
    op.drop_table('timeline')
    op.drop_table('dataversion')
    op.drop_table('post')
    op.drop_table('dataobject')
    op.drop_table('user')
    # ### end Alembic commands ###
